os: osx
language: bash
cache: bundle 
before_install: brew update
install: 
  - brew install lame
  - curl https://raw.githubusercontent.com/mklement0/voices/master/bin/voices > voices.sh
  - chmod +x voices.sh
script: 
  - cd genspeech && ./genspeech EN && cd ..
  - say -v ?
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: downloads
  on:
    branch: master
