os: osx
language: bash
cache: bundle 
before_install: brew update
install: 
  - brew install lame
  - curl https://raw.githubusercontent.com/mklement0/voices/master/bin/voices > voices.sh
  - chmod +x voices.sh
script: 
  - cd genspeech
  - ./genspeech EN Alex
  - ./genspeech EN Allison
  - ./genspeech FR Thomas
  - ./genspeech FR Amelie
  - ./genspeech DE Anna
  - cd ..
  - say -v ?
before_deploy:
  - mkdir genspeech/zip
  - mv genspeech/*.zip genspeech/zip/
deploy:
  provider: pages
  repo: TheRealMoeder/TheRealMoeder.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: genspeech/zip
  on:
    branch: master
