os: osx
language: bash
cache: bundle 
before_install: brew update
install: 
  - brew install lame
  - curl https://raw.githubusercontent.com/mklement0/voices/master/bin/voices > voices.sh
  - chmod +x voices.sh
script: 
  - cd genspeech && ./genspeech EN && cd ..
  - say -v ?
before_deploy:
  - mkdir genspeech/zip
  - mv genspeech/*.zip genspeech/zip/*.zip
deploy:
  provider: pages
  repo: TheRealMoeder.github.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: genspeech/zip
  on:
    branch: master
